# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - greater-moment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://greatermomentacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_261cb1d986f3459c8a9b668f9a207f0a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d2e02f1d5d004f8b89843876827b5378 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: greatermomentacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_261cb1d986f3459c8a9b668f9a207f0a }}/greatermoment7125:${{ github.sha }}
        file: ./Dockerfile

    - name: Build the Docker image
      run: docker build --tag angular-node-image .

    # - name: Run the Docker image
    #   run: docker run -p 3080:3080 --name ang-node-ui angular-node-image

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'greater-moment'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1070ce86224246b2be8b9d3b97d9af8f }}
        images: 'greatermomentacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_261cb1d986f3459c8a9b668f9a207f0a }}/greatermoment7125:${{ github.sha }}'
